INSERT INTO bldb.events VALUES(null, "January Fundraiser", 100, 10, 5, 5, "/img/src", "A Fundraiser", "15/01/2019");
INSERT INTO bldb.events VALUES(null, "Charity Event", 50, 3, 1, 2, "/img/src", "Another Event", "01/02/2019");
INSERT INTO bldb.volunteer VALUES(null, "Jack", "Smith", "M", 23, "Newcastle University");
INSERT INTO bldb.volunteer VALUES(null, "Jacky", "Stevens", "F", 30, "Newcastle University");
INSERT INTO bldb.volunteer VALUES(null, "John", "Daim", "M", 26, "N/A");
INSERT INTO bldb.volunteer VALUES(null, "Joanne", "Degree", "F", 21, "Teeside University");
INSERT INTO bldb.volunteer VALUES(null, "Margaret", "Davies", "F", 62, "N/A");
INSERT INTO bldb.volunteerevents VALUES(2,1);
INSERT INTO bldb.volunteerevents VALUES(2,2);
INSERT INTO bldb.volunteerevents VALUES(2,3);
INSERT INTO bldb.volunteerevents VALUES(2,4);
INSERT INTO bldb.volunteerevents VALUES(2,5);
INSERT INTO bldb.volunteerevents VALUES(2,6);
INSERT INTO bldb.volunteerevents VALUES(2,7);
INSERT INTO bldb.volunteerevents VALUES(2,8);
INSERT INTO bldb.volunteerevents VALUES(2,9);
INSERT INTO bldb.volunteerevents VALUES(2,10);
INSERT INTO bldb.volunteerevents VALUES(3,1);
INSERT INTO bldb.volunteerevents VALUES(3,2);
INSERT INTO bldb.volunteerevents VALUES(3,3);
INSERT INTO bldb.volunteerevents VALUES(3,4);
INSERT INTO bldb.volunteerevents VALUES(3,5);
INSERT INTO bldb.volunteerevents VALUES(3,6);
INSERT INTO bldb.volunteerevents VALUES(3,7);
INSERT INTO bldb.volunteerevents VALUES(3,8);
INSERT INTO bldb.volunteerevents VALUES(3,9);
INSERT INTO bldb.volunteerevents VALUES(3,10);
INSERT INTO bldb.posts VALUES(null, "Post Example 1", "This is the first example post.", "04/01/2019");
INSERT INTO bldb.posts VALUES(null, "Post Example 2", "This is the second example post.", "05/01/2019");
INSERT INTO bldb.posts VALUES(null, "Post Example 3", "This is the third example post.", "06/01/2019");
INSERT INTO bldb.posts VALUES(null, "Post Example 4", "This is the fourth example post.", "07/01/2019");
INSERT INTO bldb.testimonials VALUES(null, "Joanne Degree", "This is a testimonial", "/img/src");
INSERT INTO bldb.testimonials VALUES(null, "Margaret Davies", "This is another testimonial", "/img/src");
INSERT INTO bldb.testimonials VALUES(null, "John Daim", "This is yet another testimonial", "/img/src");