USE bldb;
INSERT INTO events VALUES(1, "Winter Ball", 1000, 5, 3, 2);
INSERT INTO volunteer VALUES(1, "Emma", "Hall", "F", 20, "Durham University");
INSERT INTO volunteer VALUES(2, "Jamie", "Bedman", "M", 22, "Durham University");
INSERT INTO volunteer VALUES(3, "John", "Smith", "M", 36, "N/A");
INSERT INTO volunteer VALUES(4, "Jack", "Mainley", "M", 18, "N/A");
INSERT INTO volunteer VALUES(5, "Jane", "Longley", "F", 40, "N/A");
INSERT INTO volunteerevents VALUES(1,1);
INSERT INTO volunteerevents VALUES(1,2);
INSERT INTO volunteerevents VALUES(1,3);
INSERT INTO volunteerevents VALUES(1,4);
INSERT INTO volunteerevents VALUES(1,5);